### ISSUE TITLE
Homepage - Leadins Area: Based from the project scope next to the "Got questions? We have answers" leadin should be a Video which can be updated at the Business Details and open in a Fancy box and not a leadin, same thing happen in the pages mentioned below

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#21]
Affected pages: About us, Brands We Supply, For Businesses, For Personal Use, Privacy Policy, Secure Shopping & Shipping Information 

![image](https://cloud.githubusercontent.com/assets/13363508/10300792/dfeeeb38-6c2d-11e5-9f89-528ef8a987f8.png)

**Comment by asif-titan** [comment]
As per Nicole's,  Email saying that there is no video as shown in the design, i have changed the video to a second lead-in.
![lead-ins](https://cloud.githubusercontent.com/assets/13450796/10571737/914cef2a-765f-11e5-8c32-1af9c8259c73.png)
