### ISSUE TITLE
Shop Listing View, Shop Sub-Category & Shop Single View: Ordered and un-ordered list does not style properly

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#22]
![image](https://cloud.githubusercontent.com/assets/13363508/10300978/46554bea-6c30-11e5-9fd9-1d93062b9281.png)

**Comment by asif-titan** [comment]
When pasting from word documents the content is not being added as ordered list or un-ordered list but as paragraph tags with line breaks, that is the reason list styles are not being applied to these.

![screenshot](https://cloud.githubusercontent.com/assets/13450796/10575370/80751744-7679-11e5-9515-4f6d26af4697.PNG)
