### ISSUE TITLE
Shop: Missing "Load More" button infinite scrolling after 12 categories shows

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#24]
![image](https://cloud.githubusercontent.com/assets/13363508/10301195/70c86d1a-6c32-11e5-8cdf-4047c0eafa6b.png)

**Comment by asif-titan** [comment]
As per Salman's Discussion with Chris, Chris said that as per titan's standards all the categories should be displayed on a single page and that categories should not be paginated, if there is no pagination then infinite scroll will also not work.

**Comment by maehtitan** [comment]
Thanks for the clarification @asif-titan . Kindly update the project scope please.

Thanks
