### ISSUE TITLE
Admin - Pages: Unable to Edit homepage, no home page found

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#31]
![image](https://cloud.githubusercontent.com/assets/13363508/10301966/4d52cddc-6c3a-11e5-8654-d80e91b2a50c.png)

**Comment by asif-titan** [comment]
The Home page is on the next page, if you move forward to the next page by clicking 2 or next in the pagination.

![admin - home page](https://cloud.githubusercontent.com/assets/13450796/10576370/645c9314-7680-11e5-8457-636a08cced5f.png)
