### ISSUE TITLE
Homepage - Mobile: Ipad view has different render for font-family main menu

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#61]
Device: 
Ipad (portrait & landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/10330570/90050f2a-6d00-11e5-9e00-8a664192e102.png)

**Comment by maehtitan** [comment]
Still not fixed

**Comment by maehtitan** [comment]
Sorry but still not fixed

**Comment by asif-titan** [comment]
As the font "myriad pro" used in the design is a pro / premium font there is no available web font format available with us, when i asked Kodi to provide me with the font this is what he / she replied back,
"
Unfortunately, after my quick search I only found a paid option to get the web version of Myriad Pro à https://typekit.com/fonts/myriad-pro
 
Alternatively there is a free alternative to Myriad Pro which you can grab here à
https://www.google.com/fonts/specimen/Droid+Sans
 
"
so can i use alternative font instead?
