### ISSUE TITLE
Gallery: Why is it that it is mentioned in the scope "pagination" but it is a load more button infinite scrolling found from the design provided

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#76]
![image](https://cloud.githubusercontent.com/assets/13363508/10355738/fea040ca-6da1-11e5-9276-cb17e263a145.png)

**Comment by asif-titan** [comment]
Infinite Scroll is not supported by Nextgen Gallery, that is the reason it mentioned as pagination in the scope.
