### ISSUE TITLE
Shop Single View: Viewing an image in a fancy-box will make the image smaller instead of viewing it in larger view ( ex. featured image when not click is much bigger compared to the pop up image ) and creates a big space at the bottom when viewing a bigger file size image

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#91]
Device: Ipad (portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/10779196/5aa9e38c-7d68-11e5-963c-c983317874b1.png)

Devices: S4 & Itouch (portrait & landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/10779322/158f0780-7d6a-11e5-891e-4e48754c016d.png)

**Comment by asif-titan** [comment]
I have fixed the space issue, regarding the image being small, please see bug #69 where you had raised the issue that the image is being stretched, to fix that i have set the lightbox container to be smaller so now the other images of different orientation are being resized to show the full image.
