### ISSUE TITLE
Shop Single View: Opening the featured image/thumbnail images in portrait view and switching the position to landscape view will not make the fancy box pop up images align to center, it will align to center when you silide the image up

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Georgie-and-Co#92]
Device: Ipad(landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/10779229/be0b0348-7d68-11e5-8801-21874c2fb639.png)

Device: S4(landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/10779345/6a2ec6fe-7d6a-11e5-981c-a776ebe23ada.png)
![image](https://cloud.githubusercontent.com/assets/13363508/10779347/6c513476-7d6a-11e5-9ad3-154434a31b09.png)

Device: Itouch(landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/10779352/7b011aa4-7d6a-11e5-8b60-435a6d4668a3.png)
![image](https://cloud.githubusercontent.com/assets/13363508/10779355/8717f790-7d6a-11e5-8444-fa17504062da.png)

**Comment by asif-titan** [comment]
This is an issue with the pretty photo plugin, will have to change the core files of the plugin.
